export enum TransactionType {
    BRANCH_DEPOSIT = 'BRANCH_DEPOSIT',
    ATM_DEPOSIT = 'ATM_DEPOSIT',
    OTHER_ACCOUNT_DEPOSIT = 'OTHER_ACCOUNT_DEPOSIT',
    PHYSICAL_PURCHASE = 'PHYSICAL_PURCHASE',
    ONLINE_PURCHASE = 'ONLINE_PURCHASE',
    ATM_WITHDRAWAL = 'ATM_WITHDRAWAL'
}